cl::BufferRenderGL
NAME
cl::BufferRenderGL -
Memory buffer interface for GL interop with renderbuffer.
SYNOPSIS
#include <cl.hpp>
Inherits cl::Buffer.
Public Types
typedef cl_mem cl_type
Public Member Functions
BufferRenderGL (const Context &context, cl_mem_flags flags, GLuint bufobj, cl_int *err=NULL)
BufferRenderGL ()
BufferRenderGL (const BufferGL &buffer)
BufferRenderGL & operator= (const BufferRenderGL &rhs)
cl_int getObjectInfo (cl_gl_object_type *type, GLuint *gl_object_name)
template<typename T > cl_int getInfo (cl_mem_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_mem_info, name >::param_type getInfo (cl_int *err=NULL) const
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Memory buffer interface for GL interop with renderbuffer.
Definition at line 1893 of file cl.hpp.
Member Typedef Documentation
typedef cl_mem cl::detail::Wrapper< cl_mem >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::BufferRenderGL::BufferRenderGL (const Context &context, cl_mem_flagsflags, GLuintbufobj, cl_int *err = NULL) [inline]
Definition at line 1896 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_mem >::object_.
cl::BufferRenderGL::BufferRenderGL () [inline]
Definition at line 1915 of file cl.hpp.
cl::BufferRenderGL::BufferRenderGL (const BufferGL &buffer) [inline]
Definition at line 1917 of file cl.hpp.
Member Function Documentation
template<typename T > cl_int cl::Memory::getInfo (cl_mem_infoname, T *param) const [inline, inherited]
Definition at line 1701 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_mem >::object_.
Referenced by cl::Memory::getInfo().
template<cl_int name> detail::param_traits<detail::cl_mem_info, name>::param_type cl::Memory::getInfo (cl_int *err = NULL) const [inline, inherited]
Definition at line 1710 of file cl.hpp.
References cl::Memory::getInfo().
cl_int cl::BufferRenderGL::getObjectInfo (cl_gl_object_type *type, GLuint *gl_object_name) [inline]
Definition at line 1927 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_mem >::object_.
cl_type cl::detail::Wrapper< cl_mem >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
cl_type& cl::detail::Wrapper< cl_mem >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
BufferRenderGL& cl::BufferRenderGL::operator= (const BufferRenderGL &rhs) [inline]
Definition at line 1919 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_mem >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_mem >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
Member Data Documentation
cl_type cl::detail::Wrapper< cl_mem >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by cl::BufferGL::BufferGL(), BufferRenderGL(), cl::Image::getImageInfo(), cl::Memory::getInfo(), getObjectInfo(), cl::BufferGL::getObjectInfo(), cl::Image2D::Image2D(), cl::Image2DGL::Image2DGL(), cl::Image3D::Image3D(), and cl::Image3DGL::Image3DGL().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.