cl::Buffer
NAME
cl::Buffer -
Memory buffer interface.
SYNOPSIS
#include <cl.hpp>
Inherits cl::Memory.
Inherited by cl::BufferGL, and cl::BufferRenderGL.
Public Types
typedef cl_mem cl_type
Public Member Functions
Buffer (const Context &context, cl_mem_flags flags,::size_t size, void *host_ptr=NULL, cl_int *err=NULL)
Buffer ()
Buffer (const Buffer &buffer)
Buffer & operator= (const Buffer &rhs)
template<typename T > cl_int getInfo (cl_mem_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_mem_info, name >::param_type getInfo (cl_int *err=NULL) const
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Memory buffer interface.
Definition at line 1742 of file cl.hpp.
Member Typedef Documentation
typedef cl_mem cl::detail::Wrapper< cl_mem >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::Buffer::Buffer (const Context &context, cl_mem_flagsflags, ::size_tsize, void *host_ptr = NULL, cl_int *err = NULL) [inline]
Definition at line 1745 of file cl.hpp.
References cl::detail::errHandler().
cl::Buffer::Buffer () [inline]
Definition at line 1761 of file cl.hpp.
cl::Buffer::Buffer (const Buffer &buffer) [inline]
Definition at line 1763 of file cl.hpp.
Member Function Documentation
template<typename T > cl_int cl::Memory::getInfo (cl_mem_infoname, T *param) const [inline, inherited]
Definition at line 1701 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_mem >::object_.
Referenced by cl::Memory::getInfo().
template<cl_int name> detail::param_traits<detail::cl_mem_info, name>::param_type cl::Memory::getInfo (cl_int *err = NULL) const [inline, inherited]
Definition at line 1710 of file cl.hpp.
References cl::Memory::getInfo().
cl_type cl::detail::Wrapper< cl_mem >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
cl_type& cl::detail::Wrapper< cl_mem >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
Buffer& cl::Buffer::operator= (const Buffer &rhs) [inline]
Definition at line 1765 of file cl.hpp.
References cl::Memory::operator=().
cl_int cl::detail::Wrapper< cl_mem >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_mem >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
Member Data Documentation
cl_type cl::detail::Wrapper< cl_mem >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by cl::BufferGL::BufferGL(), cl::BufferRenderGL::BufferRenderGL(), cl::Image::getImageInfo(), cl::Memory::getInfo(), cl::BufferRenderGL::getObjectInfo(), cl::BufferGL::getObjectInfo(), cl::Image2D::Image2D(), cl::Image2DGL::Image2DGL(), cl::Image3D::Image3D(), and cl::Image3DGL::Image3DGL().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.