.TH "cl::BufferGL" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::BufferGL \- 
.PP
\fBMemory\fP buffer interface for GL interop.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.PP
Inherits \fBcl::Buffer\fP.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef cl_mem \fBcl_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBufferGL\fP (const \fBContext\fP &context, cl_mem_flags flags, GLuint bufobj, cl_int *err=NULL)"
.br
.ti -1c
.RI "\fBBufferGL\fP ()"
.br
.ti -1c
.RI "\fBBufferGL\fP (const \fBBufferGL\fP &buffer)"
.br
.ti -1c
.RI "\fBBufferGL\fP & \fBoperator=\fP (const \fBBufferGL\fP &rhs)"
.br
.ti -1c
.RI "cl_int \fBgetObjectInfo\fP (cl_gl_object_type *type, GLuint *gl_object_name)"
.br
.ti -1c
.RI "template<typename T > cl_int \fBgetInfo\fP (cl_mem_info name, T *param) const "
.br
.ti -1c
.RI "template<cl_int name> \fBdetail::param_traits\fP< detail::cl_mem_info, name >::param_type \fBgetInfo\fP (cl_int *err=NULL) const "
.br
.ti -1c
.RI "\fBcl_type\fP \fBoperator()\fP () const"
.br
.ti -1c
.RI "\fBcl_type\fP & \fBoperator()\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "cl_int \fBretain\fP () const"
.br
.ti -1c
.RI "cl_int \fBrelease\fP () const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBcl_type\fP \fBobject_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMemory\fP buffer interface for GL interop. 
.PP
Definition at line 1846 of file cl.hpp.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef cl_mem  \fBcl::detail::Wrapper\fP< cl_mem  >::\fBcl_type\fP\fC [inherited]\fP"
.PP
Definition at line 1094 of file cl.hpp.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cl::BufferGL::BufferGL (const \fBContext\fP &context, cl_mem_flagsflags, GLuintbufobj, cl_int *err = \fCNULL\fP)\fC [inline]\fP"
.PP
Definition at line 1849 of file cl.hpp.
.PP
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_mem >::object_.
.SS "cl::BufferGL::BufferGL ()\fC [inline]\fP"
.PP
Definition at line 1868 of file cl.hpp.
.SS "cl::BufferGL::BufferGL (const \fBBufferGL\fP &buffer)\fC [inline]\fP"
.PP
Definition at line 1870 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > cl_int cl::Memory::getInfo (cl_mem_infoname, T *param) const\fC [inline, inherited]\fP"
.PP
Definition at line 1701 of file cl.hpp.
.PP
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_mem >::object_.
.PP
Referenced by cl::Memory::getInfo().
.SS "template<cl_int name> \fBdetail::param_traits\fP<detail::cl_mem_info, name>::param_type cl::Memory::getInfo (cl_int *err = \fCNULL\fP) const\fC [inline, inherited]\fP"
.PP
Definition at line 1710 of file cl.hpp.
.PP
References cl::Memory::getInfo().
.SS "cl_int cl::BufferGL::getObjectInfo (cl_gl_object_type *type, GLuint *gl_object_name)\fC [inline]\fP"
.PP
Definition at line 1880 of file cl.hpp.
.PP
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_mem >::object_.
.SS "\fBcl_type\fP \fBcl::detail::Wrapper\fP< cl_mem  >::operator() () const\fC [inline, inherited]\fP"
.PP
Definition at line 1121 of file cl.hpp.
.SS "\fBcl_type\fP& \fBcl::detail::Wrapper\fP< cl_mem  >::operator() ()\fC [inline, inherited]\fP"
.PP
Definition at line 1123 of file cl.hpp.
.SS "\fBBufferGL\fP& cl::BufferGL::operator= (const \fBBufferGL\fP &rhs)\fC [inline]\fP"
.PP
Definition at line 1872 of file cl.hpp.
.SS "cl_int \fBcl::detail::Wrapper\fP< cl_mem  >::release () const\fC [inline, protected, inherited]\fP"
.PP
Definition at line 1132 of file cl.hpp.
.SS "cl_int \fBcl::detail::Wrapper\fP< cl_mem  >::retain () const\fC [inline, protected, inherited]\fP"
.PP
Definition at line 1127 of file cl.hpp.
.SH "Member Data Documentation"
.PP 
.SS "\fBcl_type\fP \fBcl::detail::Wrapper\fP< cl_mem  >::\fBobject_\fP\fC [protected, inherited]\fP"
.PP
Definition at line 1097 of file cl.hpp.
.PP
Referenced by BufferGL(), cl::BufferRenderGL::BufferRenderGL(), cl::Image::getImageInfo(), cl::Memory::getInfo(), cl::BufferRenderGL::getObjectInfo(), getObjectInfo(), cl::Image2D::Image2D(), cl::Image2DGL::Image2DGL(), cl::Image3D::Image3D(), and cl::Image3DGL::Image3DGL().

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
