cl::Context
NAME
cl::Context -
SYNOPSIS
#include <cl.hpp>
Inherits Wrapper< cl_context >.
Public Types
typedef cl_context cl_type
Public Member Functions
Context (const VECTOR_CLASS< Device > &devices, cl_context_properties *properties=NULL, void(CL_CALLBACK *notifyFptr)(const char *, const void *,::size_t, void *)=NULL, void *data=NULL, cl_int *err=NULL)
Context (cl_device_type type, cl_context_properties *properties=NULL, void(CL_CALLBACK *notifyFptr)(const char *, const void *,::size_t, void *)=NULL, void *data=NULL, cl_int *err=NULL)
Context ()
Context (const Context &context)
Context & operator= (const Context &rhs)
template<typename T > cl_int getInfo (cl_context_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_context_info, name >::param_type getInfo (cl_int *err=NULL) const
cl_int getSupportedImageFormats (cl_mem_flags flags, cl_mem_object_type type, VECTOR_CLASS< ImageFormat > *formats) const
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Definition at line 1418 of file cl.hpp.
Member Typedef Documentation
typedef cl_context cl::detail::Wrapper< cl_context >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::Context::Context (const VECTOR_CLASS< Device > &devices, cl_context_properties *properties = NULL, void(CL_CALLBACK *notifyFptr)(const char *,const void *,::size_t,void *) = NULL, void *data = NULL, cl_int *err = NULL) [inline]
Definition at line 1421 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_context >::object_.
cl::Context::Context (cl_device_typetype, cl_context_properties *properties = NULL, void(CL_CALLBACK *notifyFptr)(const char *,const void *,::size_t,void *) = NULL, void *data = NULL, cl_int *err = NULL) [inline]
Definition at line 1444 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_context >::object_.
cl::Context::Context () [inline]
Definition at line 1465 of file cl.hpp.
cl::Context::Context (const Context &context) [inline]
Definition at line 1467 of file cl.hpp.
Member Function Documentation
template<typename T > cl_int cl::Context::getInfo (cl_context_infoname, T *param) const [inline]
Definition at line 1478 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_context >::object_.
Referenced by getInfo(), and operator<<().
template<cl_int name> detail::param_traits<detail::cl_context_info, name>::param_type cl::Context::getInfo (cl_int *err = NULL) const [inline]
Definition at line 1487 of file cl.hpp.
References getInfo().
cl_int cl::Context::getSupportedImageFormats (cl_mem_flagsflags, cl_mem_object_typetype, VECTOR_CLASS< ImageFormat > *formats) const [inline]
Definition at line 1498 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_context >::object_.
cl_type cl::detail::Wrapper< cl_context >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
cl_type& cl::detail::Wrapper< cl_context >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
Context& cl::Context::operator= (const Context &rhs) [inline]
Definition at line 1469 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_context >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_context >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
Member Data Documentation
cl_type cl::detail::Wrapper< cl_context >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by Context(), getInfo(), and getSupportedImageFormats().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.