cl::CommandQueue
NAME
cl::CommandQueue -
CommandQueue interface for cl_command_queue.
SYNOPSIS
#include <cl.hpp>
Inherits Wrapper< cl_command_queue >.
Public Types
typedef cl_command_queue cl_type
Public Member Functions
CommandQueue (const Context &context, const Device &device, cl_command_queue_properties properties=0, cl_int *err=NULL)
CommandQueue ()
CommandQueue (const CommandQueue &commandQueue)
CommandQueue & operator= (const CommandQueue &rhs)
template<typename T > cl_int getInfo (cl_command_queue_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_command_queue_info, name >::param_type getInfo (cl_int *err=NULL) const
cl_int enqueueReadBuffer (const Buffer &buffer, cl_bool blocking,::size_t offset,::size_t size, void *ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueWriteBuffer (const Buffer &buffer, cl_bool blocking,::size_t offset,::size_t size, const void *ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueCopyBuffer (const Buffer &src, const Buffer &dst,::size_t src_offset,::size_t dst_offset,::size_t size, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueReadImage (const Image &image, cl_bool blocking, const size_t< 3 > &origin, const size_t< 3 > &region,::size_t row_pitch,::size_t slice_pitch, void *ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueWriteImage (const Image &image, cl_bool blocking, const size_t< 3 > &origin, const size_t< 3 > &region,::size_t row_pitch,::size_t slice_pitch, void *ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueCopyImage (const Image &src, const Image &dst, const size_t< 3 > &src_origin, const size_t< 3 > &dst_origin, const size_t< 3 > &region, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueCopyImageToBuffer (const Image &src, const Buffer &dst, const size_t< 3 > &src_origin, const size_t< 3 > &region,::size_t dst_offset, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueCopyBufferToImage (const Buffer &src, const Image &dst,::size_t src_offset, const size_t< 3 > &dst_origin, const size_t< 3 > &region, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
void * enqueueMapBuffer (const Buffer &buffer, cl_bool blocking, cl_map_flags flags,::size_t offset,::size_t size, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL, cl_int *err=NULL) const
void * enqueueMapImage (const Image &buffer, cl_bool blocking, cl_map_flags flags, const size_t< 3 > &origin, const size_t< 3 > &region,::size_t *row_pitch,::size_t *slice_pitch, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL, cl_int *err=NULL) const
cl_int enqueueUnmapMemObject (const Memory &memory, void *mapped_ptr, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueNDRangeKernel (const Kernel &kernel, const NDRange &offset, const NDRange &global, const NDRange &local, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueTask (const Kernel &kernel, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueNativeKernel (void(*userFptr)(void *), std::pair< void *,::size_t > args, const VECTOR_CLASS< Memory > *mem_objects=NULL, const VECTOR_CLASS< const void * > *mem_locs=NULL, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueMarker (Event *event=NULL) const
cl_int enqueueWaitForEvents (const VECTOR_CLASS< Event > &events) const
cl_int enqueueAcquireGLObjects (const VECTOR_CLASS< Memory > *mem_objects=NULL, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueReleaseGLObjects (const VECTOR_CLASS< Memory > *mem_objects=NULL, const VECTOR_CLASS< Event > *events=NULL, Event *event=NULL) const
cl_int enqueueBarrier () const
cl_int flush () const
cl_int finish () const
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
CommandQueue interface for cl_command_queue.
Definition at line 2560 of file cl.hpp.
Member Typedef Documentation
typedef cl_command_queue cl::detail::Wrapper< cl_command_queue >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::CommandQueue::CommandQueue (const Context &context, const Device &device, cl_command_queue_propertiesproperties = 0, cl_int *err = NULL) [inline]
Definition at line 2563 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl::CommandQueue::CommandQueue () [inline]
Definition at line 2579 of file cl.hpp.
cl::CommandQueue::CommandQueue (const CommandQueue &commandQueue) [inline]
Definition at line 2581 of file cl.hpp.
Member Function Documentation
cl_int cl::CommandQueue::enqueueAcquireGLObjects (const VECTOR_CLASS< Memory > *mem_objects = NULL, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 3018 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueBarrier () const [inline]
Definition at line 3099 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueCopyBuffer (const Buffer &src, const Buffer &dst, ::size_tsrc_offset, ::size_tdst_offset, ::size_tsize, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2651 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
cl_int cl::CommandQueue::enqueueCopyBufferToImage (const Buffer &src, const Image &dst, ::size_tsrc_offset, const size_t< 3 > &dst_origin, const size_t< 3 > &region, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2849 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
cl_int cl::CommandQueue::enqueueCopyImage (const Image &src, const Image &dst, const size_t< 3 > &src_origin, const size_t< 3 > &dst_origin, const size_t< 3 > &region, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2811 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
cl_int cl::CommandQueue::enqueueCopyImageToBuffer (const Image &src, const Buffer &dst, const size_t< 3 > &src_origin, const size_t< 3 > &region, ::size_tdst_offset, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2830 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
void* cl::CommandQueue::enqueueMapBuffer (const Buffer &buffer, cl_boolblocking, cl_map_flagsflags, ::size_toffset, ::size_tsize, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL, cl_int *err = NULL) const [inline]
Definition at line 2868 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
void* cl::CommandQueue::enqueueMapImage (const Image &buffer, cl_boolblocking, cl_map_flagsflags, const size_t< 3 > &origin, const size_t< 3 > &region, ::size_t *row_pitch, ::size_t *slice_pitch, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL, cl_int *err = NULL) const [inline]
Definition at line 2893 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
cl_int cl::CommandQueue::enqueueMarker (Event *event = NULL) const [inline]
Definition at line 3001 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueNativeKernel (void(*)(void *)userFptr, std::pair< void *,::size_t >args, const VECTOR_CLASS< Memory > *mem_objects = NULL, const VECTOR_CLASS< const void * > *mem_locs = NULL, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2971 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueNDRangeKernel (const Kernel &kernel, const NDRange &offset, const NDRange &global, const NDRange &local, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2937 of file cl.hpp.
References cl::NDRange::dimensions(), cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
Referenced by cl::KernelFunctor::operator()().
cl_int cl::CommandQueue::enqueueReadBuffer (const Buffer &buffer, cl_boolblocking, ::size_toffset, ::size_tsize, void *ptr, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2613 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
cl_int cl::CommandQueue::enqueueReadImage (const Image &image, cl_boolblocking, const size_t< 3 > &origin, const size_t< 3 > &region, ::size_trow_pitch, ::size_tslice_pitch, void *ptr, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2769 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
cl_int cl::CommandQueue::enqueueReleaseGLObjects (const VECTOR_CLASS< Memory > *mem_objects = NULL, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 3034 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueTask (const Kernel &kernel, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2957 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueUnmapMemObject (const Memory &memory, void *mapped_ptr, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2922 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueWaitForEvents (const VECTOR_CLASS< Event > &events) const [inline]
Definition at line 3008 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::enqueueWriteBuffer (const Buffer &buffer, cl_boolblocking, ::size_toffset, ::size_tsize, const void *ptr, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2632 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
cl_int cl::CommandQueue::enqueueWriteImage (const Image &image, cl_boolblocking, const size_t< 3 > &origin, const size_t< 3 > &region, ::size_trow_pitch, ::size_tslice_pitch, void *ptr, const VECTOR_CLASS< Event > *events = NULL, Event *event = NULL) const [inline]
Definition at line 2790 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::Wrapper< cl_command_queue >::object_, and cl::vector< T, N >::size().
cl_int cl::CommandQueue::finish () const [inline]
Definition at line 3111 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
cl_int cl::CommandQueue::flush () const [inline]
Definition at line 3106 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_command_queue >::object_.
template<cl_int name> detail::param_traits<detail::cl_command_queue_info, name>::param_type cl::CommandQueue::getInfo (cl_int *err = NULL) const [inline]
Definition at line 2602 of file cl.hpp.
References getInfo().
template<typename T > cl_int cl::CommandQueue::getInfo (cl_command_queue_infoname, T *param) const [inline]
Definition at line 2592 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_command_queue >::object_.
Referenced by getInfo(), and operator<<().
cl_type& cl::detail::Wrapper< cl_command_queue >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
cl_type cl::detail::Wrapper< cl_command_queue >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
CommandQueue& cl::CommandQueue::operator= (const CommandQueue &rhs) [inline]
Definition at line 2583 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_command_queue >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_command_queue >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
Member Data Documentation
cl_type cl::detail::Wrapper< cl_command_queue >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by CommandQueue(), enqueueAcquireGLObjects(), enqueueBarrier(), enqueueCopyBuffer(), enqueueCopyBufferToImage(), enqueueCopyImage(), enqueueCopyImageToBuffer(), enqueueMapBuffer(), enqueueMapImage(), enqueueMarker(), enqueueNativeKernel(), enqueueNDRangeKernel(), enqueueReadBuffer(), enqueueReadImage(), enqueueReleaseGLObjects(), enqueueTask(), enqueueUnmapMemObject(), enqueueWaitForEvents(), enqueueWriteBuffer(), enqueueWriteImage(), finish(), flush(), and getInfo().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.