.TH "cl::detail::GetInfoHelper< Func, VECTOR_CLASS< char * > >" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::GetInfoHelper< Func, VECTOR_CLASS< char * > > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static cl_int \fBget\fP (Func f, cl_uint name, VECTOR_CLASS< char * > *param)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Func> struct cl::detail::GetInfoHelper< Func, VECTOR_CLASS< char * > >"

.PP
Definition at line 724 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Func > static cl_int \fBcl::detail::GetInfoHelper\fP< Func, VECTOR_CLASS< char * > >::get (Funcf, cl_uintname, VECTOR_CLASS< char * > *param)\fC [inline, static]\fP"
.PP
Definition at line 727 of file cl.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
