.TH "cl::detail::GetInfoHelper" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::GetInfoHelper \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static cl_int \fBget\fP (Functor f, cl_uint name, T *param)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Functor, typename T> struct cl::detail::GetInfoHelper< Functor, T >"

.PP
Definition at line 690 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Functor, typename T> static cl_int \fBcl::detail::GetInfoHelper\fP< Functor, T >::get (Functorf, cl_uintname, T *param)\fC [inline, static]\fP"
.PP
Definition at line 693 of file cl.hpp.
.PP
Referenced by cl::detail::getInfo().

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
