cl::Device
NAME
cl::Device -
Device interface for cl_device_id.
SYNOPSIS
#include <cl.hpp>
Inherits Wrapper< cl_device_id >.
Public Types
typedef cl_device_id cl_type
Public Member Functions
Device (cl_device_id device)
Device ()
Device (const Device &device)
Device & operator= (const Device &rhs)
template<typename T > cl_int getInfo (cl_device_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_device_info, name >::param_type getInfo (cl_int *err=NULL) const
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Device interface for cl_device_id.
Definition at line 1184 of file cl.hpp.
Member Typedef Documentation
typedef cl_device_id cl::detail::Wrapper< cl_device_id >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::Device::Device (cl_device_iddevice) [inline]
Definition at line 1187 of file cl.hpp.
References cl::detail::Wrapper< cl_device_id >::object_.
cl::Device::Device () [inline]
Definition at line 1189 of file cl.hpp.
cl::Device::Device (const Device &device) [inline]
Definition at line 1191 of file cl.hpp.
Member Function Documentation
template<typename T > cl_int cl::Device::getInfo (cl_device_infoname, T *param) const [inline]
Definition at line 1202 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_device_id >::object_.
Referenced by getInfo(), and operator<<().
template<cl_int name> detail::param_traits<detail::cl_device_info, name>::param_type cl::Device::getInfo (cl_int *err = NULL) const [inline]
Definition at line 1211 of file cl.hpp.
References getInfo().
cl_type cl::detail::Wrapper< cl_device_id >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
cl_type& cl::detail::Wrapper< cl_device_id >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
Device& cl::Device::operator= (const Device &rhs) [inline]
Definition at line 1193 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_device_id >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_device_id >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
Member Data Documentation
cl_type cl::detail::Wrapper< cl_device_id >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by Device(), and getInfo().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.