.TH "cl::detail::KernelArgumentHandler" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::KernelArgumentHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "::\fBsize_t\fP \fBsize\fP (const T &)"
.br
.ti -1c
.RI "static T * \fBptr\fP (T &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T> struct cl::detail::KernelArgumentHandler< T >"

.PP
Definition at line 2262 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static T* \fBcl::detail::KernelArgumentHandler\fP< T >::ptr (T &value)\fC [inline, static]\fP"
.PP
Definition at line 2265 of file cl.hpp.
.SS "template<typename T > ::\fBsize_t\fP \fBcl::detail::KernelArgumentHandler\fP< T >::size (const T &)\fC [inline, static]\fP"
.PP
Definition at line 2264 of file cl.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
