.TH "cl::detail::ReferenceHandler< cl_mem >" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::ReferenceHandler< cl_mem > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static cl_int \fBretain\fP (cl_mem memory)"
.br
.ti -1c
.RI "static cl_int \fBrelease\fP (cl_mem memory)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<> struct cl::detail::ReferenceHandler< cl_mem >"

.PP
Definition at line 1046 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "static cl_int \fBcl::detail::ReferenceHandler\fP< cl_mem >::release (cl_memmemory)\fC [inline, static]\fP"
.PP
Definition at line 1050 of file cl.hpp.
.SS "static cl_int \fBcl::detail::ReferenceHandler\fP< cl_mem >::retain (cl_memmemory)\fC [inline, static]\fP"
.PP
Definition at line 1048 of file cl.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
