cl::detail::Wrapper
NAME
cl::detail::Wrapper -
SYNOPSIS
#include <cl.hpp>
Public Types
typedef T cl_type
Public Member Functions
Wrapper ()
~Wrapper ()
Wrapper (const Wrapper< cl_type > &rhs)
Wrapper< cl_type > & operator= (const Wrapper< cl_type > &rhs)
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
template<typename T> class cl::detail::Wrapper< T >
Definition at line 1091 of file cl.hpp.
Member Typedef Documentation
template<typename T> typedef T cl::detail::Wrapper< T >::cl_type
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
template<typename T> cl::detail::Wrapper< T >::Wrapper () [inline]
Definition at line 1100 of file cl.hpp.
template<typename T> cl::detail::Wrapper< T >::~Wrapper () [inline]
Definition at line 1102 of file cl.hpp.
template<typename T> cl::detail::Wrapper< T >::Wrapper (const Wrapper< cl_type > &rhs) [inline]
Definition at line 1107 of file cl.hpp.
Member Function Documentation
template<typename T> cl_type cl::detail::Wrapper< T >::operator() () const [inline]
Definition at line 1121 of file cl.hpp.
template<typename T> cl_type& cl::detail::Wrapper< T >::operator() () [inline]
Definition at line 1123 of file cl.hpp.
template<typename T> Wrapper<cl_type>& cl::detail::Wrapper< T >::operator= (const Wrapper< cl_type > &rhs) [inline]
Definition at line 1113 of file cl.hpp.
Referenced by cl::Program::operator=(), and cl::Event::operator=().
template<typename T> cl_int cl::detail::Wrapper< T >::release () const [inline, protected]
Definition at line 1132 of file cl.hpp.
Referenced by cl::detail::Wrapper< cl_platform_id >::operator=(), cl::detail::Wrapper< cl_platform_id >::release(), and cl::detail::Wrapper< cl_platform_id >::~Wrapper().
template<typename T> cl_int cl::detail::Wrapper< T >::retain () const [inline, protected]
Definition at line 1127 of file cl.hpp.
Referenced by cl::detail::Wrapper< cl_platform_id >::operator=(), cl::detail::Wrapper< cl_platform_id >::retain(), and cl::detail::Wrapper< cl_platform_id >::Wrapper().
Member Data Documentation
template<typename T> cl_type cl::detail::Wrapper< T >::object_ [protected]
Definition at line 1097 of file cl.hpp.
Referenced by cl::detail::Wrapper< cl_platform_id >::operator()(), cl::detail::Wrapper< cl_platform_id >::operator=(), cl::detail::Wrapper< cl_platform_id >::release(), cl::detail::Wrapper< cl_platform_id >::retain(), cl::detail::Wrapper< cl_platform_id >::Wrapper(), and cl::detail::Wrapper< cl_platform_id >::~Wrapper().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.