.TH "cl::detail::ReferenceHandler< cl_device_id >" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::ReferenceHandler< cl_device_id > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static cl_int \fBretain\fP (cl_device_id)"
.br
.ti -1c
.RI "static cl_int \fBrelease\fP (cl_device_id)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<> struct cl::detail::ReferenceHandler< cl_device_id >"

.PP
Definition at line 1006 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "static cl_int \fBcl::detail::ReferenceHandler\fP< cl_device_id >::release (cl_device_id)\fC [inline, static]\fP"
.PP
Definition at line 1012 of file cl.hpp.
.SS "static cl_int \fBcl::detail::ReferenceHandler\fP< cl_device_id >::retain (cl_device_id)\fC [inline, static]\fP"
.PP
Definition at line 1009 of file cl.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
