.TH "cl::detail::GetInfoFunctor1" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::GetInfoFunctor1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "cl_int \fBoperator()\fP (cl_uint param,::\fBsize_t\fP size, void *value,::\fBsize_t\fP *size_ret)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Func \fBf_\fP"
.br
.ti -1c
.RI "const Arg0 & \fBarg0_\fP"
.br
.ti -1c
.RI "const Arg1 & \fBarg1_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Func, typename Arg0, typename Arg1> struct cl::detail::GetInfoFunctor1< Func, Arg0, Arg1 >"

.PP
Definition at line 975 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Func, typename Arg0, typename Arg1> cl_int \fBcl::detail::GetInfoFunctor1\fP< Func, Arg0, Arg1 >::operator() (cl_uintparam, ::\fBsize_t\fPsize, void *value, ::\fBsize_t\fP *size_ret)\fC [inline]\fP"
.PP
Definition at line 978 of file cl.hpp.
.PP
References cl::detail::GetInfoFunctor1< Func, Arg0, Arg1 >::arg0_, cl::detail::GetInfoFunctor1< Func, Arg0, Arg1 >::arg1_, and cl::detail::GetInfoFunctor1< Func, Arg0, Arg1 >::f_.
.SH "Member Data Documentation"
.PP 
.SS "template<typename Func, typename Arg0, typename Arg1> const Arg0& \fBcl::detail::GetInfoFunctor1\fP< Func, Arg0, Arg1 >::\fBarg0_\fP"
.PP
Definition at line 977 of file cl.hpp.
.PP
Referenced by cl::detail::GetInfoFunctor1< Func, Arg0, Arg1 >::operator()().
.SS "template<typename Func, typename Arg0, typename Arg1> const Arg1& \fBcl::detail::GetInfoFunctor1\fP< Func, Arg0, Arg1 >::\fBarg1_\fP"
.PP
Definition at line 977 of file cl.hpp.
.PP
Referenced by cl::detail::GetInfoFunctor1< Func, Arg0, Arg1 >::operator()().
.SS "template<typename Func, typename Arg0, typename Arg1> Func \fBcl::detail::GetInfoFunctor1\fP< Func, Arg0, Arg1 >::\fBf_\fP"
.PP
Definition at line 977 of file cl.hpp.
.PP
Referenced by cl::detail::GetInfoFunctor1< Func, Arg0, Arg1 >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
