.TH "cl::detail::KernelArgumentHandler< LocalSpaceArg >" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::KernelArgumentHandler< LocalSpaceArg > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "::\fBsize_t\fP \fBsize\fP (const \fBLocalSpaceArg\fP &value)"
.br
.ti -1c
.RI "static void * \fBptr\fP (\fBLocalSpaceArg\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<> struct cl::detail::KernelArgumentHandler< LocalSpaceArg >"

.PP
Definition at line 2269 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "static void* \fBcl::detail::KernelArgumentHandler\fP< \fBLocalSpaceArg\fP >::ptr (\fBLocalSpaceArg\fP &)\fC [inline, static]\fP"
.PP
Definition at line 2272 of file cl.hpp.
.SS "::\fBsize_t\fP \fBcl::detail::KernelArgumentHandler\fP< \fBLocalSpaceArg\fP >::size (const \fBLocalSpaceArg\fP &value)\fC [inline, static]\fP"
.PP
Definition at line 2271 of file cl.hpp.
.PP
References cl::LocalSpaceArg::size_.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
