.TH "cl::detail::ReferenceHandler" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::ReferenceHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename T> struct cl::detail::ReferenceHandler< T >"

.PP
Definition at line 1002 of file cl.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
