.TH "cl::detail::GetInfoHelper< Func, STRING_CLASS >" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::GetInfoHelper< Func, STRING_CLASS > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static cl_int \fBget\fP (Func f, cl_uint name, \fBSTRING_CLASS\fP *param)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Func> struct cl::detail::GetInfoHelper< Func, STRING_CLASS >"

.PP
Definition at line 740 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "template<typename Func > static cl_int \fBcl::detail::GetInfoHelper\fP< Func, \fBSTRING_CLASS\fP >::get (Funcf, cl_uintname, \fBSTRING_CLASS\fP *param)\fC [inline, static]\fP"
.PP
Definition at line 742 of file cl.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
