.TH "cl::detail::param_traits" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::param_traits \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename enum_type, cl_int Name> struct cl::detail::param_traits< enum_type, Name >"

.PP
Definition at line 934 of file cl.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
