.TH "cl::detail::ReferenceHandler< cl_command_queue >" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::detail::ReferenceHandler< cl_command_queue > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static cl_int \fBretain\fP (cl_command_queue queue)"
.br
.ti -1c
.RI "static cl_int \fBrelease\fP (cl_command_queue queue)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<> struct cl::detail::ReferenceHandler< cl_command_queue >"

.PP
Definition at line 1037 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "static cl_int \fBcl::detail::ReferenceHandler\fP< cl_command_queue >::release (cl_command_queuequeue)\fC [inline, static]\fP"
.PP
Definition at line 1041 of file cl.hpp.
.SS "static cl_int \fBcl::detail::ReferenceHandler\fP< cl_command_queue >::retain (cl_command_queuequeue)\fC [inline, static]\fP"
.PP
Definition at line 1039 of file cl.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
