cl::Event
NAME
cl::Event -
Event interface for cl_event.
SYNOPSIS
#include <cl.hpp>
Inherits Wrapper< cl_event >.
Public Types
typedef cl_event cl_type
Public Member Functions
Event ()
Event (const Event &event)
Event & operator= (const Event &rhs)
template<typename T > cl_int getInfo (cl_event_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_event_info, name >::param_type getInfo (cl_int *err=NULL) const
template<typename T > cl_int getProfilingInfo (cl_profiling_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_profiling_info, name >::param_type getProfilingInfo (cl_int *err=NULL) const
cl_int wait () const
cl_type operator() () const
cl_type & operator() ()
Static Public Member Functions
static cl_int waitForEvents (const VECTOR_CLASS< Event > &events)
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Event interface for cl_event.
Definition at line 1538 of file cl.hpp.
Member Typedef Documentation
typedef cl_event cl::detail::Wrapper< cl_event >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::Event::Event () [inline]
Definition at line 1541 of file cl.hpp.
cl::Event::Event (const Event &event) [inline]
Definition at line 1543 of file cl.hpp.
Member Function Documentation
template<typename T > cl_int cl::Event::getInfo (cl_event_infoname, T *param) const [inline]
Definition at line 1554 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::getInfo().
template<cl_int name> detail::param_traits<detail::cl_event_info, name>::param_type cl::Event::getInfo (cl_int *err = NULL) const [inline]
Definition at line 1563 of file cl.hpp.
References cl::detail::getInfo().
template<typename T > cl_int cl::Event::getProfilingInfo (cl_profiling_infoname, T *param) const [inline]
Definition at line 1575 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::getInfo().
template<cl_int name> detail::param_traits<detail::cl_profiling_info, name>::param_type cl::Event::getProfilingInfo (cl_int *err = NULL) const [inline]
Definition at line 1584 of file cl.hpp.
cl_type& cl::detail::Wrapper< cl_event >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
cl_type cl::detail::Wrapper< cl_event >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
Event& cl::Event::operator= (const Event &rhs) [inline]
Definition at line 1545 of file cl.hpp.
References cl::detail::Wrapper< T >::operator=().
cl_int cl::detail::Wrapper< cl_event >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_event >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
cl_int cl::Event::wait () const [inline]
Definition at line 1595 of file cl.hpp.
References cl::detail::errHandler().
static cl_int cl::Event::waitForEvents (const VECTOR_CLASS< Event > &events) [inline, static]
Definition at line 1619 of file cl.hpp.
References cl::detail::errHandler().
Member Data Documentation
cl_type cl::detail::Wrapper< cl_event >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Author
Generated automatically by Doxygen for cryo-opencl from the source code.