.TH "cl::ImageFormat" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::ImageFormat \- 
.PP
\fBImageFormat\fP interface fro cl_image_format.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImageFormat\fP ()"
.br
.ti -1c
.RI "\fBImageFormat\fP (cl_channel_order order, cl_channel_type type)"
.br
.ti -1c
.RI "\fBImageFormat\fP & \fBoperator=\fP (const \fBImageFormat\fP &rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBImageFormat\fP interface fro cl_image_format. 

\fBImageFormat\fP 
.PP
Definition at line 1161 of file cl.hpp.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cl::ImageFormat::ImageFormat ()\fC [inline]\fP"
.PP
Definition at line 1163 of file cl.hpp.
.SS "cl::ImageFormat::ImageFormat (cl_channel_orderorder, cl_channel_typetype)\fC [inline]\fP"
.PP
Definition at line 1165 of file cl.hpp.
.SH "Member Function Documentation"
.PP 
.SS "\fBImageFormat\fP& cl::ImageFormat::operator= (const \fBImageFormat\fP &rhs)\fC [inline]\fP"
.PP
Definition at line 1171 of file cl.hpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
