cl::Image2D
NAME
cl::Image2D -
Image interface for 2D images.
SYNOPSIS
#include <cl.hpp>
Inherits cl::Image.
Inherited by cl::Image2DGL.
Public Types
typedef cl_mem cl_type
Public Member Functions
Image2D (const Context &context, cl_mem_flags flags, ImageFormat format,::size_t width,::size_t height,::size_t row_pitch=0, void *host_ptr=NULL, cl_int *err=NULL)
Image2D ()
Image2D (const Image2D &image2D)
Image2D & operator= (const Image2D &rhs)
template<typename T > cl_int getImageInfo (cl_image_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_image_info, name >::param_type getImageInfo (cl_int *err=NULL) const
template<typename T > cl_int getInfo (cl_mem_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_mem_info, name >::param_type getInfo (cl_int *err=NULL) const
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Image interface for 2D images.
Definition at line 1980 of file cl.hpp.
Member Typedef Documentation
typedef cl_mem cl::detail::Wrapper< cl_mem >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::Image2D::Image2D (const Context &context, cl_mem_flagsflags, ImageFormatformat, ::size_twidth, ::size_theight, ::size_trow_pitch = 0, void *host_ptr = NULL, cl_int *err = NULL) [inline]
Definition at line 1983 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_mem >::object_.
cl::Image2D::Image2D () [inline]
Definition at line 2003 of file cl.hpp.
cl::Image2D::Image2D (const Image2D &image2D) [inline]
Definition at line 2005 of file cl.hpp.
Member Function Documentation
template<typename T > cl_int cl::Image::getImageInfo (cl_image_infoname, T *param) const [inline, inherited]
Definition at line 1956 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_mem >::object_.
Referenced by cl::Image::getImageInfo().
template<cl_int name> detail::param_traits<detail::cl_image_info, name>::param_type cl::Image::getImageInfo (cl_int *err = NULL) const [inline, inherited]
Definition at line 1965 of file cl.hpp.
References cl::Image::getImageInfo().
template<typename T > cl_int cl::Memory::getInfo (cl_mem_infoname, T *param) const [inline, inherited]
Definition at line 1701 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_mem >::object_.
Referenced by cl::Memory::getInfo().
template<cl_int name> detail::param_traits<detail::cl_mem_info, name>::param_type cl::Memory::getInfo (cl_int *err = NULL) const [inline, inherited]
Definition at line 1710 of file cl.hpp.
References cl::Memory::getInfo().
cl_type& cl::detail::Wrapper< cl_mem >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
cl_type cl::detail::Wrapper< cl_mem >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
Image2D& cl::Image2D::operator= (const Image2D &rhs) [inline]
Definition at line 2007 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_mem >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_mem >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
Member Data Documentation
cl_type cl::detail::Wrapper< cl_mem >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by cl::BufferGL::BufferGL(), cl::BufferRenderGL::BufferRenderGL(), cl::Image::getImageInfo(), cl::Memory::getInfo(), cl::BufferRenderGL::getObjectInfo(), cl::BufferGL::getObjectInfo(), Image2D(), cl::Image2DGL::Image2DGL(), cl::Image3D::Image3D(), and cl::Image3DGL::Image3DGL().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.