cl::Kernel
NAME
cl::Kernel -
Kernel interface that implements cl_kernel.
SYNOPSIS
#include <cl.hpp>
Inherits Wrapper< cl_kernel >.
Public Types
typedef cl_kernel cl_type
Public Member Functions
Kernel (const Program &program, const char *name, cl_int *err=NULL)
Kernel ()
Kernel (const Kernel &kernel)
Kernel & operator= (const Kernel &rhs)
template<typename T > cl_int getInfo (cl_kernel_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_kernel_info, name >::param_type getInfo (cl_int *err=NULL) const
template<typename T > cl_int getWorkGroupInfo (const Device &device, cl_kernel_work_group_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_kernel_work_group_info, name >::param_type getWorkGroupInfo (const Device &device, cl_int *err=NULL) const
template<typename T > cl_int setArg (cl_uint index, T value)
cl_int setArg (cl_uint index,::size_t size, void *argPtr)
KernelFunctor bind (const CommandQueue &queue, const NDRange &offset, const NDRange &global, const NDRange &local)
KernelFunctor bind (const CommandQueue &queue, const NDRange &global, const NDRange &local)
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Kernel interface that implements cl_kernel.
Definition at line 2290 of file cl.hpp.
Member Typedef Documentation
typedef cl_kernel cl::detail::Wrapper< cl_kernel >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::Kernel::Kernel (const Program &program, const char *name, cl_int *err = NULL) [inline]
Definition at line 2544 of file cl.hpp.
References cl::detail::errHandler().
cl::Kernel::Kernel () [inline]
Definition at line 2295 of file cl.hpp.
cl::Kernel::Kernel (const Kernel &kernel) [inline]
Definition at line 2297 of file cl.hpp.
Member Function Documentation
KernelFunctor cl::Kernel::bind (const CommandQueue &queue, const NDRange &offset, const NDRange &global, const NDRange &local) [inline]
Definition at line 3356 of file cl.hpp.
KernelFunctor cl::Kernel::bind (const CommandQueue &queue, const NDRange &global, const NDRange &local) [inline]
Definition at line 3365 of file cl.hpp.
References cl::NullRange.
template<typename T > cl_int cl::Kernel::getInfo (cl_kernel_infoname, T *param) const [inline]
Definition at line 2308 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_kernel >::object_.
Referenced by getInfo(), and operator<<().
template<cl_int name> detail::param_traits<detail::cl_kernel_info, name>::param_type cl::Kernel::getInfo (cl_int *err = NULL) const [inline]
Definition at line 2317 of file cl.hpp.
References getInfo().
template<typename T > cl_int cl::Kernel::getWorkGroupInfo (const Device &device, cl_kernel_work_group_infoname, T *param) const [inline]
Definition at line 2329 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_kernel >::object_.
Referenced by getWorkGroupInfo().
template<cl_int name> detail::param_traits<detail::cl_kernel_work_group_info, name>::param_type cl::Kernel::getWorkGroupInfo (const Device &device, cl_int *err = NULL) const [inline]
Definition at line 2340 of file cl.hpp.
References getWorkGroupInfo().
cl_type cl::detail::Wrapper< cl_kernel >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
cl_type& cl::detail::Wrapper< cl_kernel >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
Kernel& cl::Kernel::operator= (const Kernel &rhs) [inline]
Definition at line 2299 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_kernel >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_kernel >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
cl_int cl::Kernel::setArg (cl_uintindex, ::size_tsize, void *argPtr) [inline]
Definition at line 2363 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_kernel >::object_.
template<typename T > cl_int cl::Kernel::setArg (cl_uintindex, Tvalue) [inline]
Definition at line 2352 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_kernel >::object_.
Referenced by cl::KernelFunctor::operator()().
Member Data Documentation
cl_type cl::detail::Wrapper< cl_kernel >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by getInfo(), getWorkGroupInfo(), and setArg().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.