.TH "cl::LocalSpaceArg" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cl::LocalSpaceArg \- 
.PP
Local address raper for use with \fBKernel::setArg\fP.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cl.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "::\fBsize_t\fP \fBsize_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Local address raper for use with \fBKernel::setArg\fP. 
.PP
Definition at line 2254 of file cl.hpp.
.SH "Member Data Documentation"
.PP 
.SS "::\fBsize_t\fP \fBcl::LocalSpaceArg::size_\fP"
.PP
Definition at line 2256 of file cl.hpp.
.PP
Referenced by cl::detail::KernelArgumentHandler< LocalSpaceArg >::size().

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
