cl::Memory
NAME
cl::Memory -
Memory interface for cl_mem.
SYNOPSIS
#include <cl.hpp>
Inherits Wrapper< cl_mem >.
Inherited by cl::Buffer, and cl::Image.
Public Types
typedef cl_mem cl_type
Public Member Functions
Memory ()
Memory (const Memory &memory)
Memory & operator= (const Memory &rhs)
template<typename T > cl_int getInfo (cl_mem_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_mem_info, name >::param_type getInfo (cl_int *err=NULL) const
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Memory interface for cl_mem.
Definition at line 1685 of file cl.hpp.
Member Typedef Documentation
typedef cl_mem cl::detail::Wrapper< cl_mem >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::Memory::Memory () [inline]
Definition at line 1688 of file cl.hpp.
cl::Memory::Memory (const Memory &memory) [inline]
Definition at line 1690 of file cl.hpp.
Member Function Documentation
template<typename T > cl_int cl::Memory::getInfo (cl_mem_infoname, T *param) const [inline]
Definition at line 1701 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_mem >::object_.
Referenced by getInfo().
template<cl_int name> detail::param_traits<detail::cl_mem_info, name>::param_type cl::Memory::getInfo (cl_int *err = NULL) const [inline]
Definition at line 1710 of file cl.hpp.
References getInfo().
cl_type cl::detail::Wrapper< cl_mem >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
cl_type& cl::detail::Wrapper< cl_mem >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
Memory& cl::Memory::operator= (const Memory &rhs) [inline]
Definition at line 1692 of file cl.hpp.
Referenced by cl::Buffer::operator=().
cl_int cl::detail::Wrapper< cl_mem >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_mem >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
Member Data Documentation
cl_type cl::detail::Wrapper< cl_mem >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by cl::BufferGL::BufferGL(), cl::BufferRenderGL::BufferRenderGL(), cl::Image::getImageInfo(), getInfo(), cl::BufferRenderGL::getObjectInfo(), cl::BufferGL::getObjectInfo(), cl::Image2D::Image2D(), cl::Image2DGL::Image2DGL(), cl::Image3D::Image3D(), and cl::Image3DGL::Image3DGL().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.