cl::NDRange
NAME
cl::NDRange -
NDRange interface.
SYNOPSIS
#include <cl.hpp>
Public Member Functions
NDRange ()
NDRange (::size_t size0)
NDRange (::size_t size0,::size_t size1)
NDRange (::size_t size0,::size_t size1,::size_t size2)
operator const ::size_t * () const
::size_t dimensions () const
Private Attributes
size_t< 3 > sizes_
cl_uint dimensions_
Detailed Description
NDRange interface.
Definition at line 2212 of file cl.hpp.
Constructor & Destructor Documentation
cl::NDRange::NDRange () [inline]
Definition at line 2219 of file cl.hpp.
cl::NDRange::NDRange (::size_tsize0) [inline]
Definition at line 2223 of file cl.hpp.
References cl::vector< T, N >::push_back().
cl::NDRange::NDRange (::size_tsize0, ::size_tsize1) [inline]
Definition at line 2229 of file cl.hpp.
References cl::vector< T, N >::push_back().
cl::NDRange::NDRange (::size_tsize0, ::size_tsize1, ::size_tsize2) [inline]
Definition at line 2236 of file cl.hpp.
References cl::vector< T, N >::push_back().
Member Function Documentation
::size_t cl::NDRange::dimensions () const [inline]
Definition at line 2245 of file cl.hpp.
Referenced by cl::CommandQueue::enqueueNDRangeKernel().
cl::NDRange::operator const ::size_t * () const [inline]
Definition at line 2244 of file cl.hpp.
Member Data Documentation
cl_uint cl::NDRange::dimensions_ [private]
Definition at line 2216 of file cl.hpp.
size_t<3> cl::NDRange::sizes_ [private]
Definition at line 2215 of file cl.hpp.
Author
Generated automatically by Doxygen for cryo-opencl from the source code.