cl::Program
NAME
cl::Program -
Program interface that implements cl_program.
SYNOPSIS
#include <cl.hpp>
Inherits Wrapper< cl_program >.
Public Types
typedef VECTOR_CLASS< std::pair< const void *,::size_t > > Binaries
typedef VECTOR_CLASS< std::pair< const char *,::size_t > > Sources
typedef cl_program cl_type
Public Member Functions
Program (const Context &context, const Sources &sources, cl_int *err=NULL)
Program (const Context &context, const VECTOR_CLASS< Device > &devices, const Binaries &binaries, VECTOR_CLASS< cl_int > *binaryStatus=NULL, cl_int *err=NULL)
Program ()
Program (const Program &program)
Program & operator= (const Program &rhs)
cl_int build (const VECTOR_CLASS< Device > &devices, const char *options=NULL, void(CL_CALLBACK *notifyFptr)(cl_program, void *)=NULL, void *data=NULL) const
template<typename T > cl_int getInfo (cl_program_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_program_info, name >::param_type getInfo (cl_int *err=NULL) const
template<typename T > cl_int getBuildInfo (const Device &device, cl_program_build_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_program_build_info, name >::param_type getBuildInfo (const Device &device, cl_int *err=NULL) const
cl_int createKernels (VECTOR_CLASS< Kernel > *kernels)
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Program interface that implements cl_program.
Definition at line 2387 of file cl.hpp.
Member Typedef Documentation
typedef VECTOR_CLASS<std::pair<const void*, ::size_t> > cl::Program::Binaries
Definition at line 2390 of file cl.hpp.
typedef cl_program cl::detail::Wrapper< cl_program >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
typedef VECTOR_CLASS<std::pair<const char*, ::size_t> > cl::Program::Sources
Definition at line 2391 of file cl.hpp.
Constructor & Destructor Documentation
cl::Program::Program (const Context &context, const Sources &sources, cl_int *err = NULL) [inline]
Definition at line 2393 of file cl.hpp.
References cl::detail::errHandler().
cl::Program::Program (const Context &context, const VECTOR_CLASS< Device > &devices, const Binaries &binaries, VECTOR_CLASS< cl_int > *binaryStatus = NULL, cl_int *err = NULL) [inline]
Definition at line 2418 of file cl.hpp.
References cl::detail::errHandler().
cl::Program::Program () [inline]
Definition at line 2448 of file cl.hpp.
cl::Program::Program (const Program &program) [inline]
Definition at line 2450 of file cl.hpp.
Member Function Documentation
cl_int cl::Program::build (const VECTOR_CLASS< Device > &devices, const char *options = NULL, void(CL_CALLBACK *notifyFptr)(cl_program, void *) = NULL, void *data = NULL) const [inline]
Definition at line 2460 of file cl.hpp.
References cl::detail::errHandler().
Referenced by cryo::OpenCLManager::compileKernel().
cl_int cl::Program::createKernels (VECTOR_CLASS< Kernel > *kernels) [inline]
Definition at line 2522 of file cl.hpp.
References cl::detail::errHandler().
template<typename T > cl_int cl::Program::getBuildInfo (const Device &device, cl_program_build_infoname, T *param) const [inline]
Definition at line 2500 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::getInfo().
Referenced by cryo::OpenCLManager::compileKernel().
template<cl_int name> detail::param_traits<detail::cl_program_build_info, name>::param_type cl::Program::getBuildInfo (const Device &device, cl_int *err = NULL) const [inline]
Definition at line 2511 of file cl.hpp.
template<cl_int name> detail::param_traits<detail::cl_program_info, name>::param_type cl::Program::getInfo (cl_int *err = NULL) const [inline]
Definition at line 2488 of file cl.hpp.
References cl::detail::getInfo().
template<typename T > cl_int cl::Program::getInfo (cl_program_infoname, T *param) const [inline]
Definition at line 2479 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::getInfo().
cl_type cl::detail::Wrapper< cl_program >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
cl_type& cl::detail::Wrapper< cl_program >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
Program& cl::Program::operator= (const Program &rhs) [inline]
Definition at line 2452 of file cl.hpp.
References cl::detail::Wrapper< T >::operator=().
cl_int cl::detail::Wrapper< cl_program >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_program >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
Member Data Documentation
cl_type cl::detail::Wrapper< cl_program >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Author
Generated automatically by Doxygen for cryo-opencl from the source code.