cl::Platform
NAME
cl::Platform -
Platform interface.
SYNOPSIS
#include <cl.hpp>
Inherits Wrapper< cl_platform_id >.
Public Types
typedef cl_platform_id cl_type
Public Member Functions
Platform (cl_platform_id platform)
Platform ()
Platform (const Platform &platform)
Platform & operator= (const Platform &rhs)
cl_int getInfo (cl_platform_info name, STRING_CLASS *param) const
template<cl_int name> detail::param_traits< detail::cl_platform_info, name >::param_type getInfo (cl_int *err=NULL) const
cl_int getDevices (cl_device_type type, VECTOR_CLASS< Device > *devices) const
cl_type operator() () const
cl_type & operator() ()
Static Public Member Functions
static const Platform null ()
static cl_int get (VECTOR_CLASS< Platform > *platforms)
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Platform interface.
Definition at line 1259 of file cl.hpp.
Member Typedef Documentation
typedef cl_platform_id cl::detail::Wrapper< cl_platform_id >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::Platform::Platform (cl_platform_idplatform) [inline]
Definition at line 1264 of file cl.hpp.
References cl::detail::Wrapper< cl_platform_id >::object_.
cl::Platform::Platform () [inline]
Definition at line 1266 of file cl.hpp.
cl::Platform::Platform (const Platform &platform) [inline]
Definition at line 1268 of file cl.hpp.
Member Function Documentation
static cl_int cl::Platform::get (VECTOR_CLASS< Platform > *platforms) [inline, static]
Definition at line 1391 of file cl.hpp.
References cl::detail::errHandler().
Referenced by cryo::OpenCLManager::initialise().
cl_int cl::Platform::getDevices (cl_device_typetype, VECTOR_CLASS< Device > *devices) const [inline]
Definition at line 1298 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_platform_id >::object_.
cl_int cl::Platform::getInfo (cl_platform_infoname, STRING_CLASS *param) const [inline]
Definition at line 1278 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_platform_id >::object_.
Referenced by getInfo(), and operator<<().
template<cl_int name> detail::param_traits<detail::cl_platform_info, name>::param_type cl::Platform::getInfo (cl_int *err = NULL) const [inline]
Definition at line 1287 of file cl.hpp.
References getInfo().
static const Platform cl::Platform::null () [static]
cl_type& cl::detail::Wrapper< cl_platform_id >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
References cl::detail::Wrapper< T >::object_.
cl_type cl::detail::Wrapper< cl_platform_id >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
References cl::detail::Wrapper< T >::object_.
Platform& cl::Platform::operator= (const Platform &rhs) [inline]
Definition at line 1270 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_platform_id >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
References cl::detail::Wrapper< T >::object_, and cl::detail::Wrapper< T >::release().
cl_int cl::detail::Wrapper< cl_platform_id >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
References cl::detail::Wrapper< T >::object_, and cl::detail::Wrapper< T >::retain().
Member Data Documentation
cl_type cl::detail::Wrapper< cl_platform_id >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by getDevices(), getInfo(), and Platform().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.