cl::Sampler
NAME
cl::Sampler -
Sampler interface for cl_sampler.
SYNOPSIS
#include <cl.hpp>
Inherits Wrapper< cl_sampler >.
Public Types
typedef cl_sampler cl_type
Public Member Functions
Sampler ()
Sampler (const Context &context, cl_bool normalized_coords, cl_addressing_mode addressing_mode, cl_filter_mode filter_mode, cl_int *err=NULL)
Sampler (const Sampler &sampler)
Sampler & operator= (const Sampler &rhs)
template<typename T > cl_int getInfo (cl_sampler_info name, T *param) const
template<cl_int name> detail::param_traits< detail::cl_sampler_info, name >::param_type getInfo (cl_int *err=NULL) const
cl_type operator() () const
cl_type & operator() ()
Protected Member Functions
cl_int retain () const
cl_int release () const
Protected Attributes
cl_type object_
Detailed Description
Sampler interface for cl_sampler.
Definition at line 2145 of file cl.hpp.
Member Typedef Documentation
typedef cl_sampler cl::detail::Wrapper< cl_sampler >::cl_type [inherited]
Definition at line 1094 of file cl.hpp.
Constructor & Destructor Documentation
cl::Sampler::Sampler () [inline]
Definition at line 2148 of file cl.hpp.
cl::Sampler::Sampler (const Context &context, cl_boolnormalized_coords, cl_addressing_modeaddressing_mode, cl_filter_modefilter_mode, cl_int *err = NULL) [inline]
Definition at line 2150 of file cl.hpp.
References cl::detail::errHandler(), and cl::detail::Wrapper< cl_sampler >::object_.
cl::Sampler::Sampler (const Sampler &sampler) [inline]
Definition at line 2171 of file cl.hpp.
Member Function Documentation
template<typename T > cl_int cl::Sampler::getInfo (cl_sampler_infoname, T *param) const [inline]
Definition at line 2182 of file cl.hpp.
References cl::detail::errHandler(), cl::detail::getInfo(), and cl::detail::Wrapper< cl_sampler >::object_.
Referenced by getInfo().
template<cl_int name> detail::param_traits<detail::cl_sampler_info, name>::param_type cl::Sampler::getInfo (cl_int *err = NULL) const [inline]
Definition at line 2191 of file cl.hpp.
References getInfo().
cl_type cl::detail::Wrapper< cl_sampler >::operator() () const [inline, inherited]
Definition at line 1121 of file cl.hpp.
cl_type& cl::detail::Wrapper< cl_sampler >::operator() () [inline, inherited]
Definition at line 1123 of file cl.hpp.
Sampler& cl::Sampler::operator= (const Sampler &rhs) [inline]
Definition at line 2173 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_sampler >::release () const [inline, protected, inherited]
Definition at line 1132 of file cl.hpp.
cl_int cl::detail::Wrapper< cl_sampler >::retain () const [inline, protected, inherited]
Definition at line 1127 of file cl.hpp.
Member Data Documentation
cl_type cl::detail::Wrapper< cl_sampler >::object_ [protected, inherited]
Definition at line 1097 of file cl.hpp.
Referenced by getInfo(), and Sampler().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.