cl::size_t
NAME
cl::size_t -
size_t class used to interface between C++ and OpenCL C calls that require arrays of size_t values, who's size is known statically.
SYNOPSIS
#include <cl.hpp>
Inherits vector< ::size_t, N >.
Public Member Functions
unsigned int size (void) const
void clear ()
void push_back (const ::size_t &x)
void pop_back (void)
bool operator== (vector< ::size_t, N > &vec)
operator::size_t * ()
operator const ::size_t * () const
bool empty (void) const
unsigned int max_size (void) const
unsigned int capacity () const
::size_t & operator[] (int index)
::size_t operator[] (int index) const
void assign (I start, I end)
iterator begin (void)
iterator end (void)
::size_t & front (void)
const ::size_t & front (void) const
::size_t & back (void)
const ::size_t & back (void) const
Detailed Description
template<int N> struct cl::size_t< N >
size_t class used to interface between C++ and OpenCL C calls that require arrays of size_t values, who's size is known statically.
Definition at line 684 of file cl.hpp.
Member Function Documentation
void cl::vector< ::size_t , N >::assign (Istart, Iend) [inline, inherited]
Definition at line 555 of file cl.hpp.
References cl::vector< T, N >::clear(), and cl::vector< T, N >::push_back().
::size_t & cl::vector< ::size_t , N >::back (void) [inline, inherited]
Definition at line 662 of file cl.hpp.
References cl::vector< T, N >::data_, and cl::vector< T, N >::size_.
const ::size_t & cl::vector< ::size_t , N >::back (void) const [inline, inherited]
Definition at line 672 of file cl.hpp.
References cl::vector< T, N >::data_, and cl::vector< T, N >::size_.
iterator cl::vector< ::size_t , N >::begin (void) [inline, inherited]
Definition at line 647 of file cl.hpp.
References cl::vector< T, N >::iterator::begin().
unsigned int cl::vector< ::size_t , N >::capacity () const [inline, inherited]
Definition at line 539 of file cl.hpp.
void cl::vector< ::size_t , N >::clear () [inline, inherited]
Definition at line 453 of file cl.hpp.
References cl::vector< T, N >::empty_, and cl::vector< T, N >::size_.
bool cl::vector< ::size_t , N >::empty (void) const [inline, inherited]
Definition at line 529 of file cl.hpp.
References cl::vector< T, N >::empty_.
iterator cl::vector< ::size_t , N >::end (void) [inline, inherited]
Definition at line 652 of file cl.hpp.
References cl::vector< T, N >::iterator::end().
const ::size_t & cl::vector< ::size_t , N >::front (void) const [inline, inherited]
Definition at line 667 of file cl.hpp.
References cl::vector< T, N >::data_.
::size_t & cl::vector< ::size_t , N >::front (void) [inline, inherited]
Definition at line 657 of file cl.hpp.
References cl::vector< T, N >::data_.
unsigned int cl::vector< ::size_t , N >::max_size (void) const [inline, inherited]
Definition at line 534 of file cl.hpp.
cl::vector< ::size_t , N >::operator const ::size_t * () const [inline, inherited]
Definition at line 527 of file cl.hpp.
cl::vector< ::size_t , N >::operator ::size_t * () [inline, inherited]
Definition at line 526 of file cl.hpp.
References cl::vector< T, N >::data_.
bool cl::vector< ::size_t , N >::operator== (vector< ::size_t , N > &vec) [inline, inherited]
Definition at line 513 of file cl.hpp.
References cl::vector< T, N >::data_, cl::vector< T, N >::empty_, and cl::vector< T, N >::size().
::size_t & cl::vector< ::size_t , N >::operator[] (intindex) [inline, inherited]
Definition at line 544 of file cl.hpp.
References cl::vector< T, N >::data_.
::size_t cl::vector< ::size_t , N >::operator[] (intindex) const [inline, inherited]
Definition at line 549 of file cl.hpp.
References cl::vector< T, N >::data_.
void cl::vector< ::size_t , N >::pop_back (void) [inline, inherited]
Definition at line 468 of file cl.hpp.
References cl::vector< T, N >::data_, cl::vector< T, N >::empty_, and cl::vector< T, N >::size_.
void cl::vector< ::size_t , N >::push_back (const ::size_t &x) [inline, inherited]
Definition at line 459 of file cl.hpp.
References cl::vector< T, N >::data_, cl::vector< T, N >::empty_, cl::vector< T, N >::size(), and cl::vector< T, N >::size_.
unsigned int cl::vector< ::size_t , N >::size (void) const [inline, inherited]
Definition at line 448 of file cl.hpp.
References cl::vector< T, N >::size_.
Author
Generated automatically by Doxygen for cryo-opencl from the source code.