cl::vector
NAME
cl::vector -
Fixed sized vector implementation that mirroring std::vector functionality.
SYNOPSIS
#include <cl.hpp>
Classes
class iterator
Iterator class for vectors.
Public Member Functions
vector ()
~vector ()
unsigned int size (void) const
void clear ()
void push_back (const T &x)
void pop_back (void)
vector (const vector< T, N > &vec)
vector (unsigned int size, const T &val=T())
vector< T, N > & operator= (const vector< T, N > &rhs)
bool operator== (vector< T, N > &vec)
operator T * ()
operator const T * () const
bool empty (void) const
unsigned int max_size (void) const
unsigned int capacity () const
T & operator[] (int index)
T operator[] (int index) const
template<class I > void assign (I start, I end)
iterator begin (void)
iterator end (void)
T & front (void)
T & back (void)
const T & front (void) const
const T & back (void) const
Private Attributes
T data_ [N]
unsigned int size_
bool empty_
Detailed Description
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> class cl::vector< T, N >
Fixed sized vector implementation that mirroring std::vector functionality.
Definition at line 434 of file cl.hpp.
Constructor & Destructor Documentation
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> cl::vector< T, N >::vector () [inline]
Definition at line 441 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> cl::vector< T, N >::~vector () [inline]
Definition at line 446 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> cl::vector< T, N >::vector (const vector< T, N > &vec) [inline]
Definition at line 479 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> cl::vector< T, N >::vector (unsigned intsize, const T &val = T()) [inline]
Definition at line 488 of file cl.hpp.
Member Function Documentation
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> template<class I > void cl::vector< T, N >::assign (Istart, Iend) [inline]
Definition at line 555 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> T& cl::vector< T, N >::back (void) [inline]
Definition at line 662 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> const T& cl::vector< T, N >::back (void) const [inline]
Definition at line 672 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> iterator cl::vector< T, N >::begin (void) [inline]
Definition at line 647 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> unsigned int cl::vector< T, N >::capacity () const [inline]
Definition at line 539 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> void cl::vector< T, N >::clear () [inline]
Definition at line 453 of file cl.hpp.
Referenced by cl::vector< ::size_t, N >::assign().
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> bool cl::vector< T, N >::empty (void) const [inline]
Definition at line 529 of file cl.hpp.
Referenced by cl::vector< T, N >::iterator::begin(), and cl::vector< T, N >::iterator::end().
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> iterator cl::vector< T, N >::end (void) [inline]
Definition at line 652 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> T& cl::vector< T, N >::front (void) [inline]
Definition at line 657 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> const T& cl::vector< T, N >::front (void) const [inline]
Definition at line 667 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> unsigned int cl::vector< T, N >::max_size (void) const [inline]
Definition at line 534 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> cl::vector< T, N >::operator const T * () const [inline]
Definition at line 527 of file cl.hpp.
References cl::vector< T, N >::data_.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> cl::vector< T, N >::operator T * () [inline]
Definition at line 526 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> vector<T, N>& cl::vector< T, N >::operator= (const vector< T, N > &rhs) [inline]
Definition at line 497 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> bool cl::vector< T, N >::operator== (vector< T, N > &vec) [inline]
Definition at line 513 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> T cl::vector< T, N >::operator[] (intindex) const [inline]
Definition at line 549 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> T& cl::vector< T, N >::operator[] (intindex) [inline]
Definition at line 544 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> void cl::vector< T, N >::pop_back (void) [inline]
Definition at line 468 of file cl.hpp.
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> void cl::vector< T, N >::push_back (const T &x) [inline]
Definition at line 459 of file cl.hpp.
Referenced by cl::vector< ::size_t, N >::assign(), cl::NDRange::NDRange(), and cl::vector< ::size_t, N >::vector().
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> unsigned int cl::vector< T, N >::size (void) const [inline]
Definition at line 448 of file cl.hpp.
Referenced by cl::vector< T, N >::iterator::end(), cl::CommandQueue::enqueueCopyBuffer(), cl::CommandQueue::enqueueCopyBufferToImage(), cl::CommandQueue::enqueueCopyImage(), cl::CommandQueue::enqueueCopyImageToBuffer(), cl::CommandQueue::enqueueMapBuffer(), cl::CommandQueue::enqueueMapImage(), cl::CommandQueue::enqueueReadBuffer(), cl::CommandQueue::enqueueReadImage(), cl::CommandQueue::enqueueWriteBuffer(), cl::CommandQueue::enqueueWriteImage(), cl::vector< ::size_t, N >::operator==(), cl::vector< ::size_t, N >::push_back(), and cl::vector< ::size_t, N >::vector().
Member Data Documentation
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> T cl::vector< T, N >::data_[N] [private]
Definition at line 437 of file cl.hpp.
Referenced by cl::vector< ::size_t, N >::back(), cl::vector< ::size_t, N >::front(), cl::vector< T, N >::operator const T *(), cl::vector< ::size_t, N >::operator::size_t *(), cl::vector< ::size_t, N >::operator=(), cl::vector< ::size_t, N >::operator==(), cl::vector< ::size_t, N >::operator[](), cl::vector< ::size_t, N >::pop_back(), cl::vector< ::size_t, N >::push_back(), and cl::vector< ::size_t, N >::vector().
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> bool cl::vector< T, N >::empty_ [private]
Definition at line 439 of file cl.hpp.
Referenced by cl::vector< ::size_t, N >::clear(), cl::vector< ::size_t, N >::empty(), cl::vector< ::size_t, N >::operator=(), cl::vector< ::size_t, N >::operator==(), cl::vector< ::size_t, N >::pop_back(), cl::vector< ::size_t, N >::push_back(), and cl::vector< ::size_t, N >::vector().
template<typename T, unsigned int N = __MAX_DEFAULT_VECTOR_SIZE> unsigned int cl::vector< T, N >::size_ [private]
Definition at line 438 of file cl.hpp.
Referenced by cl::vector< ::size_t, N >::back(), cl::vector< ::size_t, N >::clear(), cl::vector< ::size_t, N >::operator=(), cl::vector< ::size_t, N >::pop_back(), cl::vector< ::size_t, N >::push_back(), and cl::vector< ::size_t, N >::size().
Author
Generated automatically by Doxygen for cryo-opencl from the source code.