cryo::OpenCLManager
NAME
cryo::OpenCLManager -
The OpenCLManager class deals with the bulk of setting up and tearing down opencl.
SYNOPSIS
#include <OpenCLManager.h>
Inherited by cryo::runners::NullRunner, and cryo::runners::SimpleRunner.
Public Member Functions
OpenCLManager ()
virtual ~OpenCLManager ()
virtual bool run ()=0
virtual bool loadKernelSource (const std::string ifstring)
virtual const char * oclErrorString (cl_int error)
virtual bool loadKernel (std::string kernelstring)
virtual bool compileKernel (std::string buildoptions='')
boost::shared_ptr< cl::Kernel > getMutableKernel (const std::string &name)
Get kernel by kernel name.
virtual std::string getKernelSource ()
const std::vector< cl::Platform > & getPlatforms () const
const std::vector< cl::Device > & getDevices () const
const cl::Device & getActiveDevice () const
const cl::Context & getContext () const
const std::map< std::string, boost::shared_ptr< cl::Kernel > > & getKernels () const
const cl::CommandQueue & getCommandQueue () const
const cl::Program & getProgram () const
void parseFunctionNames (const std::string &source)
std::ostream & printKernelNames (std::ostream &os)
std::ostream & printKernelSource (std::ostream &os)
std::ostream & printCLError (std::ostream &os, const cl::Error &er)
Protected Member Functions
bool initialise ()
Protected Attributes
std::string kernelSource
std::string sourceString
std::set< std::string > kernelNames
bool platform_id_success
bool device_id_success
bool kernel_compilation_success
std::vector< cl::Platform > platforms
std::vector< cl::Device > devices
std::vector< cl::Device >::const_iterator activeDevice
cl::Context context
std::map< std::string, boost::shared_ptr< cl::Kernel > > kernels
cl::CommandQueue commandQueue
cl::Program program
cl_int error
cl::Event event
Detailed Description
The OpenCLManager class deals with the bulk of setting up and tearing down opencl.
Subclasses load program source in their constructor and then should implement the run() method to actually do calculations.
Definition at line 30 of file OpenCLManager.h.
Constructor & Destructor Documentation
home niall Projects Eclipse cryo opencl src OpenCLManager cpp cryo::OpenCLManager::OpenCLManager ()
Definition at line 17 of file OpenCLManager.cpp.
cryo::OpenCLManager::~OpenCLManager () [virtual]
Definition at line 20 of file OpenCLManager.cpp.
Member Function Documentation
bool cryo::OpenCLManager::compileKernel (std::stringbuildoptions = '') [virtual]
Definition at line 161 of file OpenCLManager.cpp.
References cl::Program::build(), devices, cl::Program::getBuildInfo(), and program.
const cl::Device & cryo::OpenCLManager::getActiveDevice () const
Definition at line 40 of file OpenCLManager.cpp.
const cl::CommandQueue & cryo::OpenCLManager::getCommandQueue () const
Definition at line 49 of file OpenCLManager.cpp.
const cl::Context & cryo::OpenCLManager::getContext () const
Definition at line 43 of file OpenCLManager.cpp.
const std::vector< cl::Device > & cryo::OpenCLManager::getDevices () const
Definition at line 37 of file OpenCLManager.cpp.
const std::map< std::string, boost::shared_ptr< cl::Kernel > > & cryo::OpenCLManager::getKernels () const
Definition at line 46 of file OpenCLManager.cpp.
std::string cryo::OpenCLManager::getKernelSource () [virtual]
Definition at line 22 of file OpenCLManager.cpp.
boost::shared_ptr< cl::Kernel > cryo::OpenCLManager::getMutableKernel (const std::string &name)
Get kernel by kernel name.
Definition at line 26 of file OpenCLManager.cpp.
const std::vector< cl::Platform > & cryo::OpenCLManager::getPlatforms () const
Definition at line 34 of file OpenCLManager.cpp.
const cl::Program & cryo::OpenCLManager::getProgram () const
Definition at line 52 of file OpenCLManager.cpp.
bool cryo::OpenCLManager::initialise () [protected]
Definition at line 79 of file OpenCLManager.cpp.
References cl::Platform::get(), and platforms.
bool cryo::OpenCLManager::loadKernel (std::stringkernelstring) [virtual]
Definition at line 233 of file OpenCLManager.cpp.
References context, and program.
Referenced by cryo::runners::NullRunner::NullRunner().
bool cryo::OpenCLManager::loadKernelSource (const std::stringifstring) [virtual]
Definition at line 134 of file OpenCLManager.cpp.
References kernelSource, parseFunctionNames(), and printKernelNames().
const char * cryo::OpenCLManager::oclErrorString (cl_interror) [virtual]
Definition at line 56 of file OpenCLManager.cpp.
void cryo::OpenCLManager::parseFunctionNames (const std::string &source)
Definition at line 260 of file OpenCLManager.cpp.
References kernelNames.
Referenced by loadKernelSource().
std::ostream & cryo::OpenCLManager::printCLError (std::ostream &os, const cl::Error &er)
Definition at line 305 of file OpenCLManager.cpp.
std::ostream & cryo::OpenCLManager::printKernelNames (std::ostream &os)
Definition at line 290 of file OpenCLManager.cpp.
References kernelNames.
Referenced by loadKernelSource().
std::ostream & cryo::OpenCLManager::printKernelSource (std::ostream &os)
Definition at line 249 of file OpenCLManager.cpp.
virtual bool cryo::OpenCLManager::run () [pure virtual]
Implemented in cryo::runners::NullRunner, and cryo::runners::SimpleRunner.
Member Data Documentation
std::vector<cl::Device>::const_iterator cryo::OpenCLManager::activeDevice [protected]
Definition at line 74 of file OpenCLManager.h.
cl::CommandQueue cryo::OpenCLManager::commandQueue [protected]
Definition at line 79 of file OpenCLManager.h.
cl::Context cryo::OpenCLManager::context [protected]
Definition at line 76 of file OpenCLManager.h.
Referenced by loadKernel().
bool cryo::OpenCLManager::device_id_success [protected]
Definition at line 68 of file OpenCLManager.h.
std::vector<cl::Device> cryo::OpenCLManager::devices [protected]
Definition at line 73 of file OpenCLManager.h.
Referenced by compileKernel().
cl_int cryo::OpenCLManager::error [protected]
Definition at line 82 of file OpenCLManager.h.
cl::Event cryo::OpenCLManager::event [protected]
Definition at line 83 of file OpenCLManager.h.
bool cryo::OpenCLManager::kernel_compilation_success [protected]
Definition at line 69 of file OpenCLManager.h.
std::set<std::string> cryo::OpenCLManager::kernelNames [protected]
Definition at line 65 of file OpenCLManager.h.
Referenced by parseFunctionNames(), and printKernelNames().
std::map<std::string, boost::shared_ptr<cl::Kernel> > cryo::OpenCLManager::kernels [protected]
Definition at line 78 of file OpenCLManager.h.
std::string cryo::OpenCLManager::kernelSource [protected]
Definition at line 63 of file OpenCLManager.h.
Referenced by loadKernelSource(), and cryo::runners::NullRunner::NullRunner().
bool cryo::OpenCLManager::platform_id_success [protected]
Definition at line 67 of file OpenCLManager.h.
std::vector<cl::Platform> cryo::OpenCLManager::platforms [protected]
Definition at line 71 of file OpenCLManager.h.
Referenced by initialise().
cl::Program cryo::OpenCLManager::program [protected]
Definition at line 80 of file OpenCLManager.h.
Referenced by compileKernel(), and loadKernel().
std::string cryo::OpenCLManager::sourceString [protected]
Definition at line 64 of file OpenCLManager.h.
Author
Generated automatically by Doxygen for cryo-opencl from the source code.