.TH "cryo::runners" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryo::runners \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNullRunner\fP"
.br
.RI "\fINull runner will not allow running the cl code but allows us to instantiate a manager for other uses. \fP"
.ti -1c
.RI "class \fBSimpleRunner\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
