cryo::runners::SimpleRunner
NAME
cryo::runners::SimpleRunner -
SYNOPSIS
#include <SimpleRunner.h>
Inherits cryo::OpenCLManager.
Public Member Functions
SimpleRunner ()
virtual ~SimpleRunner ()
virtual bool run ()
virtual void setUpBuffer ()
virtual bool loadKernelSource (const std::string ifstring)
virtual const char * oclErrorString (cl_int error)
virtual bool loadKernel (std::string kernelstring)
virtual bool compileKernel (std::string buildoptions='')
boost::shared_ptr< cl::Kernel > getMutableKernel (const std::string &name)
Get kernel by kernel name.
virtual std::string getKernelSource ()
const std::vector< cl::Platform > & getPlatforms () const
const std::vector< cl::Device > & getDevices () const
const cl::Device & getActiveDevice () const
const cl::Context & getContext () const
const std::map< std::string, boost::shared_ptr< cl::Kernel > > & getKernels () const
const cl::CommandQueue & getCommandQueue () const
const cl::Program & getProgram () const
void parseFunctionNames (const std::string &source)
std::ostream & printKernelNames (std::ostream &os)
std::ostream & printKernelSource (std::ostream &os)
std::ostream & printCLError (std::ostream &os, const cl::Error &er)
Protected Member Functions
bool initialise ()
Protected Attributes
cl::Buffer cl_a
cl::Buffer cl_b
cl::Buffer cl_c
int num
std::string kernelSource
std::string sourceString
std::set< std::string > kernelNames
bool platform_id_success
bool device_id_success
bool kernel_compilation_success
std::vector< cl::Platform > platforms
std::vector< cl::Device > devices
std::vector< cl::Device >::const_iterator activeDevice
cl::Context context
std::map< std::string, boost::shared_ptr< cl::Kernel > > kernels
cl::CommandQueue commandQueue
cl::Program program
cl_int error
cl::Event event
Detailed Description
Definition at line 17 of file SimpleRunner.h.
Constructor & Destructor Documentation
cryo::runners::SimpleRunner::SimpleRunner ()
Definition at line 15 of file SimpleRunner.cpp.
cryo::runners::SimpleRunner::~SimpleRunner () [virtual]
Definition at line 25 of file SimpleRunner.cpp.
Member Function Documentation
bool cryo::OpenCLManager::compileKernel (std::stringbuildoptions = '') [virtual, inherited]
Definition at line 161 of file OpenCLManager.cpp.
References cl::Program::build(), cryo::OpenCLManager::devices, cl::Program::getBuildInfo(), and cryo::OpenCLManager::program.
const cl::Device & cryo::OpenCLManager::getActiveDevice () const [inherited]
Definition at line 40 of file OpenCLManager.cpp.
const cl::CommandQueue & cryo::OpenCLManager::getCommandQueue () const [inherited]
Definition at line 49 of file OpenCLManager.cpp.
const cl::Context & cryo::OpenCLManager::getContext () const [inherited]
Definition at line 43 of file OpenCLManager.cpp.
const std::vector< cl::Device > & cryo::OpenCLManager::getDevices () const [inherited]
Definition at line 37 of file OpenCLManager.cpp.
const std::map< std::string, boost::shared_ptr< cl::Kernel > > & cryo::OpenCLManager::getKernels () const [inherited]
Definition at line 46 of file OpenCLManager.cpp.
std::string cryo::OpenCLManager::getKernelSource () [virtual, inherited]
Definition at line 22 of file OpenCLManager.cpp.
boost::shared_ptr< cl::Kernel > cryo::OpenCLManager::getMutableKernel (const std::string &name) [inherited]
Get kernel by kernel name.
Definition at line 26 of file OpenCLManager.cpp.
const std::vector< cl::Platform > & cryo::OpenCLManager::getPlatforms () const [inherited]
Definition at line 34 of file OpenCLManager.cpp.
const cl::Program & cryo::OpenCLManager::getProgram () const [inherited]
Definition at line 52 of file OpenCLManager.cpp.
bool cryo::OpenCLManager::initialise () [protected, inherited]
Definition at line 79 of file OpenCLManager.cpp.
References cl::Platform::get(), and cryo::OpenCLManager::platforms.
bool cryo::OpenCLManager::loadKernel (std::stringkernelstring) [virtual, inherited]
Definition at line 233 of file OpenCLManager.cpp.
References cryo::OpenCLManager::context, and cryo::OpenCLManager::program.
Referenced by cryo::runners::NullRunner::NullRunner().
bool cryo::OpenCLManager::loadKernelSource (const std::stringifstring) [virtual, inherited]
Definition at line 134 of file OpenCLManager.cpp.
References cryo::OpenCLManager::kernelSource, cryo::OpenCLManager::parseFunctionNames(), and cryo::OpenCLManager::printKernelNames().
const char * cryo::OpenCLManager::oclErrorString (cl_interror) [virtual, inherited]
Definition at line 56 of file OpenCLManager.cpp.
void cryo::OpenCLManager::parseFunctionNames (const std::string &source) [inherited]
Definition at line 260 of file OpenCLManager.cpp.
References cryo::OpenCLManager::kernelNames.
Referenced by cryo::OpenCLManager::loadKernelSource().
std::ostream & cryo::OpenCLManager::printCLError (std::ostream &os, const cl::Error &er) [inherited]
Definition at line 305 of file OpenCLManager.cpp.
std::ostream & cryo::OpenCLManager::printKernelNames (std::ostream &os) [inherited]
Definition at line 290 of file OpenCLManager.cpp.
References cryo::OpenCLManager::kernelNames.
Referenced by cryo::OpenCLManager::loadKernelSource().
std::ostream & cryo::OpenCLManager::printKernelSource (std::ostream &os) [inherited]
Definition at line 249 of file OpenCLManager.cpp.
bool cryo::runners::SimpleRunner::run () [virtual]
clReleaseEvent(event);
Implements cryo::OpenCLManager.
Definition at line 80 of file SimpleRunner.cpp.
void cryo::runners::SimpleRunner::setUpBuffer () [virtual]
Definition at line 28 of file SimpleRunner.cpp.
Member Data Documentation
std::vector<cl::Device>::const_iterator cryo::OpenCLManager::activeDevice [protected, inherited]
Definition at line 74 of file OpenCLManager.h.
cl::Buffer cryo::runners::SimpleRunner::cl_a [protected]
Definition at line 25 of file SimpleRunner.h.
cl::Buffer cryo::runners::SimpleRunner::cl_b [protected]
Definition at line 26 of file SimpleRunner.h.
cl::Buffer cryo::runners::SimpleRunner::cl_c [protected]
Definition at line 27 of file SimpleRunner.h.
cl::CommandQueue cryo::OpenCLManager::commandQueue [protected, inherited]
Definition at line 79 of file OpenCLManager.h.
cl::Context cryo::OpenCLManager::context [protected, inherited]
Definition at line 76 of file OpenCLManager.h.
Referenced by cryo::OpenCLManager::loadKernel().
bool cryo::OpenCLManager::device_id_success [protected, inherited]
Definition at line 68 of file OpenCLManager.h.
std::vector<cl::Device> cryo::OpenCLManager::devices [protected, inherited]
Definition at line 73 of file OpenCLManager.h.
Referenced by cryo::OpenCLManager::compileKernel().
cl_int cryo::OpenCLManager::error [protected, inherited]
Definition at line 82 of file OpenCLManager.h.
cl::Event cryo::OpenCLManager::event [protected, inherited]
Definition at line 83 of file OpenCLManager.h.
bool cryo::OpenCLManager::kernel_compilation_success [protected, inherited]
Definition at line 69 of file OpenCLManager.h.
std::set<std::string> cryo::OpenCLManager::kernelNames [protected, inherited]
Definition at line 65 of file OpenCLManager.h.
Referenced by cryo::OpenCLManager::parseFunctionNames(), and cryo::OpenCLManager::printKernelNames().
std::map<std::string, boost::shared_ptr<cl::Kernel> > cryo::OpenCLManager::kernels [protected, inherited]
Definition at line 78 of file OpenCLManager.h.
std::string cryo::OpenCLManager::kernelSource [protected, inherited]
Definition at line 63 of file OpenCLManager.h.
Referenced by cryo::OpenCLManager::loadKernelSource(), and cryo::runners::NullRunner::NullRunner().
int cryo::runners::SimpleRunner::num [protected]
Definition at line 28 of file SimpleRunner.h.
bool cryo::OpenCLManager::platform_id_success [protected, inherited]
Definition at line 67 of file OpenCLManager.h.
std::vector<cl::Platform> cryo::OpenCLManager::platforms [protected, inherited]
Definition at line 71 of file OpenCLManager.h.
Referenced by cryo::OpenCLManager::initialise().
cl::Program cryo::OpenCLManager::program [protected, inherited]
Definition at line 80 of file OpenCLManager.h.
Referenced by cryo::OpenCLManager::compileKernel(), and cryo::OpenCLManager::loadKernel().
std::string cryo::OpenCLManager::sourceString [protected, inherited]
Definition at line 64 of file OpenCLManager.h.
Author
Generated automatically by Doxygen for cryo-opencl from the source code.