.TH "cryo" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cryo \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrunners\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOpenCLManager\fP"
.br
.RI "\fIThe \fBOpenCLManager\fP class deals with the bulk of setting up and tearing down opencl. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
