.TH "/home/niall/Projects/Eclipse/cryo-opencl/src/OpenCLManager.h" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryo-opencl/src/OpenCLManager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'OpenCLPrint.h'\fP
.br
\fC#include 'CL/cl.hpp'\fP
.br
\fC#include <CL/cl.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <set>\fP
.br
\fC#include <map>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <boost/shared_ptr.hpp>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryo::OpenCLManager\fP"
.br
.RI "\fIThe \fBOpenCLManager\fP class deals with the bulk of setting up and tearing down opencl. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryo\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__CL_ENABLE_EXCEPTIONS\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define __CL_ENABLE_EXCEPTIONS"
.PP
Definition at line 10 of file OpenCLManager.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
