.TH "OpenCLPrint" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCLPrint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpenCLPrint.h>\fP
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static std::map< std::string, std::string > \fBcreateCLDefMap\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static std::map< std::string, std::string > \fBdefMap\fP = createCLDefMap()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file OpenCLPrint.h.
.SH "Member Function Documentation"
.PP 
.SS "std::map< std::string, std::string > OpenCLPrint::createCLDefMap ()\fC [static, private]\fP"
.PP
Definition at line 12 of file OpenCLPrint.cpp.
.SH "Member Data Documentation"
.PP 
.SS "std::map< std::string, std::string > \fBOpenCLPrint::defMap\fP = createCLDefMap()\fC [static, private]\fP"
.PP
Definition at line 27 of file OpenCLPrint.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
