/home/niall/Projects/Eclipse/cryo-opencl/src/OpenCLPrint.h
NAME
/home/niall/Projects/Eclipse/cryo-opencl/src/OpenCLPrint.h -
SYNOPSIS
#include <ostream>
#include 'CL/cl.hpp'
#include <string>
#include <map>
Classes
class OpenCLPrint
Functions
std::ostream & operator<< (std::ostream &os, const cl::Platform &platform)
std::ostream & operator<< (std::ostream &os, const std::vector< cl::Platform > &platforms)
std::ostream & operator<< (std::ostream &os, const cl::Device &device)
std::ostream & operator<< (std::ostream &os, const std::vector< cl::Device > &devices)
std::ostream & operator<< (std::ostream &os, const cl::Context &context)
std::ostream & operator<< (std::ostream &os, const cl::CommandQueue &queue)
std::ostream & operator<< (std::ostream &os, const cl::Kernel &kernel)
std::ostream & operator<< (std::ostream &os, const cl::Program &program)
Function Documentation
std::ostream& operator<< (std::ostream &os, const cl::Platform &platform)
Definition at line 330 of file OpenCLPrint.cpp.
References cl::Platform::getInfo().
std::ostream& operator<< (std::ostream &os, const cl::Program &program)
Definition at line 438 of file OpenCLPrint.cpp.
std::ostream& operator<< (std::ostream &os, const cl::Kernel &kernel)
Definition at line 422 of file OpenCLPrint.cpp.
References cl::Kernel::getInfo().
std::ostream& operator<< (std::ostream &os, const cl::CommandQueue &queue)
Definition at line 408 of file OpenCLPrint.cpp.
References cl::CommandQueue::getInfo().
std::ostream& operator<< (std::ostream &os, const cl::Context &context)
Definition at line 379 of file OpenCLPrint.cpp.
References cl::Context::getInfo().
std::ostream& operator<< (std::ostream &os, const std::vector< cl::Device > &devices)
Definition at line 364 of file OpenCLPrint.cpp.
std::ostream& operator<< (std::ostream &os, const cl::Device &device)
Definition at line 354 of file OpenCLPrint.cpp.
References cl::Device::getInfo().
std::ostream& operator<< (std::ostream &os, const std::vector< cl::Platform > &platforms)
Definition at line 339 of file OpenCLPrint.cpp.
Author
Generated automatically by Doxygen for cryo-opencl from the source code.