.TH "/home/niall/Projects/Eclipse/cryo-opencl/src/runners/SimpleRunner.h" 3 "Mon Mar 14 2011" "cryo-opencl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/niall/Projects/Eclipse/cryo-opencl/src/runners/SimpleRunner.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'OpenCLManager.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcryo::runners::SimpleRunner\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcryo\fP"
.br
.ti -1c
.RI "namespace \fBcryo::runners\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cryo-opencl from the source code.
